from django.urls import path
from . import views
from . import slack_views
from . import github_views
from . import outlook_views
from . import onedrive_views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("login_api/", views.login_api, name="login_api"),
    path("register/",views.register, name="register"),
    path("new_register/<str:username>/<str:password>/<str:firstName>/<str:lastName>/",views.new_register, name="new_register"),
    path("getuserinfo4/<str:username>/<str:password>/", views.getuserinfo4, name="getuserinfo4"),
    path("add_site_visitor_info/", views.add_site_visitor_info, name="add_site_visitor_info"),
    path("add_site_visitor_info_enhanced/", views.add_site_visitor_info_enhanced, name="add_site_visitor_info_enhanced"),
    path("get_site_visitor_info/", views.get_site_visitor_info, name="get_site_visitor_info"),
    path("get_site_visitor_info_enhanced/", views.get_site_visitor_info_enhanced, name="get_site_visitor_info_enhanced"),
    path("get_site_visitor_info_paginated/", views.get_site_visitor_info_paginated, name="get_site_visitor_info_paginated"),
    path("get_login_analytics/", views.get_login_analytics, name="get_login_analytics"),
    path("get_google_scopes_analytics/", views.get_google_scopes_analytics, name="get_google_scopes_analytics"),
    path("get_client_ip/", views.get_client_ip, name="get_client_ip"),
    path("google/", views.google, name="google"),
    path("auth/callback/", views.google_callback, name="google_callback"),
    path("validate-token/", views.validate_token, name="validate_token"),
    path("refresh-token/", views.refresh_token, name="refresh_token"),
    path('api-key/generate/', views.generate_user_api_key, name='generate_api_key'),
    path('api-key/validate/', views.validate_user_api_key, name='validate_api_key'),
    path('api-key/list/', views.list_api_keys, name='list_api_keys'),
    path('api-key/delete/', views.delete_user_api_key, name='delete_api_key'),
    # Browser automation
    path('browserbase/session/', views.browserbase_session, name='browserbase_session'),
    # Gmail API proxy endpoints
    path('gmail/list_messages/', views.gmail_list_messages, name='gmail_list_messages'),
    path('gmail/labels/', views.gmail_labels, name='gmail_labels'),
    path('gmail/labels/<str:label_id>/', views.gmail_label_detail, name='gmail_label_detail'),
    path('gmail/messages/<str:message_id>/', views.gmail_get_message, name='gmail_get_message'),
    path('gmail/send_message/', views.gmail_send_message, name='gmail_send_message'),
    path('gmail/messages/<str:message_id>/modify/', views.gmail_modify_message, name='gmail_modify_message'),
    # X API proxy endpoints
    path('x_api/user_info/', views.x_api_user_info, name='x_api_user_info'),
    path('x_api/user_tweets/', views.x_api_user_tweets, name='x_api_user_tweets'),
    path('x_api/search_tweets/', views.x_api_search_tweets, name='x_api_search_tweets'),
    path('x_api/trending_topics/', views.x_api_trending_topics, name='x_api_trending_topics'),
    path('x_api/post_tweet/', views.x_api_post_tweet, name='x_api_post_tweet'),
    # X OAuth2 endpoints
    path('x_api/oauth2/initiate/', views.x_api_oauth2_initiate, name='x_api_oauth2_initiate'),
    path('x_api/oauth2/callback/', views.x_api_oauth2_callback, name='x_api_oauth2_callback'),
    path('x_api/oauth2/disconnect/', views.x_api_oauth2_disconnect, name='x_api_oauth2_disconnect'),
    # X API Connection Management
    path('x_api/connection_status/', views.x_api_connection_status, name='x_api_connection_status'),
    path('x_api/initiate_oauth/', views.x_api_initiate_oauth, name='x_api_initiate_oauth'),
    path('x_api/oauth_callback/', views.x_api_oauth_callback, name='x_api_oauth_callback'),
    path('x_api/disconnect/', views.x_api_disconnect, name='x_api_disconnect'),
    path('x_api/test_connection/', views.x_api_test_connection, name='x_api_test_connection'),
    path('gmail/messages/batch', views.gmail_get_messages_batch, name='gmail_get_messages_batch'),
    path('gmail/messages/<str:message_id>/attachments/<str:attachment_id>', views.gmail_get_attachment, name='gmail_get_attachment'),
    path('gmail/test-batch', views.gmail_test_batch, name='gmail_test_batch'),
    # Gmail threading endpoints
    path('gmail/reply/', views.gmail_send_reply, name='gmail_send_reply'),
    path('gmail/thread/<str:thread_id>/', views.gmail_get_thread, name='gmail_get_thread'),
    path('gmail/threads/', views.gmail_list_threads, name='gmail_list_threads'),
    # Google Drive API proxy endpoints
    path('drive/list_files/', views.drive_list_files, name='drive_list_files'),
    path('drive/files/<str:file_id>/', views.drive_get_file, name='drive_get_file'),
    path('drive/files/<str:file_id>/download/', views.drive_download_file, name='drive_download_file'),
    path('drive/files/<str:file_id>/export/', views.drive_export_file, name='drive_export_file'),
    path('drive/files/<str:file_id>/update/', views.drive_update_file, name='drive_update_file'),
    path('drive/files/<str:file_id>/rename/', views.drive_rename_file, name='drive_rename_file'),
    path('drive/files/<str:file_id>/delete/', views.drive_delete_file, name='drive_delete_file'),
    path('drive/files/<str:file_id>/star/', views.drive_star_file, name='drive_star_file'),
    path('drive/files/<str:file_id>/unstar/', views.drive_unstar_file, name='drive_unstar_file'),
    # Google Calendar API proxy endpoints
    path('calendar/calendars/', views.calendar_calendars, name='calendar_calendars'),
    path('calendar/events/', views.calendar_events, name='calendar_events'),
    path('calendar/events/<str:event_id>/', views.calendar_event_detail, name='calendar_event_detail'),
    # Scope management endpoints
    path('scopes/user/', views.get_user_scopes, name='get_user_scopes'),
    path('scopes/request/', views.request_additional_scopes, name='request_additional_scopes'),
    path('scopes/features/', views.get_available_features, name='get_available_features'),
    # Slack OAuth endpoints
    path('slack/status/', slack_views.slack_connection_status, name='slack_connection_status'),
    path('slack/initiate_oauth/', slack_views.slack_initiate_oauth, name='slack_initiate_oauth'),
    path('slack/oauth_callback/', slack_views.slack_oauth_callback, name='slack_oauth_callback'),
    path('slack/disconnect/', slack_views.slack_disconnect, name='slack_disconnect'),
    # Slack API proxy endpoints
    path('slack/channels/', slack_views.slack_list_channels, name='slack_list_channels'),
    path('slack/send_message/', slack_views.slack_send_message, name='slack_send_message'),
    path('slack/channel_history/', slack_views.slack_channel_history, name='slack_channel_history'),
    path('slack/thread_replies/', slack_views.slack_thread_replies, name='slack_thread_replies'),
    path('slack/search/', slack_views.slack_search_messages, name='slack_search_messages'),
    path('slack/user_info/', slack_views.slack_user_info, name='slack_user_info'),
    path('slack/set_channel_topic/', slack_views.slack_set_channel_topic, name='slack_set_channel_topic'),
    path('slack/add_reaction/', slack_views.slack_add_reaction, name='slack_add_reaction'),
    # GitHub OAuth endpoints
    path('github/status/', github_views.github_connection_status, name='github_connection_status'),
    path('github/initiate_oauth/', github_views.github_initiate_oauth, name='github_initiate_oauth'),
    path('github/oauth_callback/', github_views.github_oauth_callback, name='github_oauth_callback'),
    path('github/disconnect/', github_views.github_disconnect, name='github_disconnect'),
    # GitHub API proxy endpoints
    path('github/repos/', github_views.github_list_repos, name='github_list_repos'),
    path('github/repos/<str:owner>/<str:repo>/', github_views.github_get_repo, name='github_get_repo'),
    path('github/repos/<str:owner>/<str:repo>/issues/', github_views.github_list_issues, name='github_list_issues'),
    path('github/repos/<str:owner>/<str:repo>/pulls/', github_views.github_list_pull_requests, name='github_list_pull_requests'),
    path('github/repos/<str:owner>/<str:repo>/contents/', github_views.github_get_file_contents, name='github_get_file_contents'),
    path('github/issues/create/', github_views.github_create_issue, name='github_create_issue'),
    path('github/search/code/', github_views.github_search_code, name='github_search_code'),
    # Outlook OAuth endpoints
    path('outlook/status/', outlook_views.outlook_connection_status, name='outlook_connection_status'),
    path('outlook/initiate_oauth/', outlook_views.outlook_initiate_oauth, name='outlook_initiate_oauth'),
    path('outlook/oauth_callback/', outlook_views.outlook_oauth_callback, name='outlook_oauth_callback'),
    path('outlook/disconnect/', outlook_views.outlook_disconnect, name='outlook_disconnect'),
    # Outlook Mail API proxy endpoints
    path('outlook/list_messages/', outlook_views.outlook_list_messages, name='outlook_list_messages'),
    path('outlook/messages/<str:message_id>/', outlook_views.outlook_get_message, name='outlook_get_message'),
    path('outlook/messages/batch', outlook_views.outlook_get_messages_batch, name='outlook_get_messages_batch'),
    path('outlook/folders/', outlook_views.outlook_list_folders, name='outlook_list_folders'),
    path('outlook/send_message/', outlook_views.outlook_send_message, name='outlook_send_message'),
    path('outlook/reply/', outlook_views.outlook_send_reply, name='outlook_send_reply'),
    path('outlook/messages/<str:message_id>/modify/', outlook_views.outlook_modify_message, name='outlook_modify_message'),
    path('outlook/messages/<str:message_id>/attachments/<str:attachment_id>', outlook_views.outlook_get_attachment, name='outlook_get_attachment'),
    path('outlook/thread/<str:conversation_id>/', outlook_views.outlook_get_thread, name='outlook_get_thread'),
    # Outlook Calendar API proxy endpoints
    path('outlook/calendar/status/', outlook_views.outlook_calendar_status, name='outlook_calendar_status'),
    path('outlook/calendars/', outlook_views.outlook_list_calendars, name='outlook_list_calendars'),
    path('outlook/calendar/events/', outlook_views.outlook_calendar_events, name='outlook_calendar_events'),
    path('outlook/calendar/events/<str:event_id>/', outlook_views.outlook_calendar_event_detail, name='outlook_calendar_event_detail'),
    # OneDrive OAuth endpoints
    path('onedrive/status/', onedrive_views.onedrive_connection_status, name='onedrive_connection_status'),
    path('onedrive/initiate_oauth/', onedrive_views.onedrive_initiate_oauth, name='onedrive_initiate_oauth'),
    path('onedrive/oauth_callback/', onedrive_views.onedrive_oauth_callback, name='onedrive_oauth_callback'),
    path('onedrive/disconnect/', onedrive_views.onedrive_disconnect, name='onedrive_disconnect'),
    # OneDrive file proxy endpoints (Microsoft Graph)
    path('onedrive/root/children/', onedrive_views.onedrive_list_root_children, name='onedrive_list_root_children'),
    path('onedrive/items/<str:item_id>/children/', onedrive_views.onedrive_list_item_children, name='onedrive_list_item_children'),
    path('onedrive/recent/', onedrive_views.onedrive_recent_files, name='onedrive_recent_files'),
    path('onedrive/search/', onedrive_views.onedrive_search_files, name='onedrive_search_files'),
    path('onedrive/items/<str:item_id>/', onedrive_views.onedrive_get_item, name='onedrive_get_item'),
    path('onedrive/items/<str:item_id>/download/', onedrive_views.onedrive_download_file, name='onedrive_download_file'),
    path('onedrive/items/<str:item_id>/update/', onedrive_views.onedrive_update_file, name='onedrive_update_file'),
    path('onedrive/folders/create/', onedrive_views.onedrive_create_folder, name='onedrive_create_folder'),
    path('onedrive/files/upload/', onedrive_views.onedrive_upload_file, name='onedrive_upload_file'),
    path('onedrive/items/<str:item_id>/rename_move/', onedrive_views.onedrive_rename_move, name='onedrive_rename_move'),
    path('onedrive/items/<str:item_id>/delete/', onedrive_views.onedrive_delete_item, name='onedrive_delete_item'),
    path('onedrive/items/<str:item_id>/share_link/', onedrive_views.onedrive_create_share_link, name='onedrive_create_share_link'),
    path('onedrive/items/<str:item_id>/invite/', onedrive_views.onedrive_invite, name='onedrive_invite'),
    path('onedrive/items/<str:item_id>/permissions/', onedrive_views.onedrive_get_permissions, name='onedrive_get_permissions'),
    # OneDrive Banbury-managed favorites
    path('onedrive/favorites/', onedrive_views.onedrive_favorites_list, name='onedrive_favorites_list'),
    path('onedrive/favorites/<str:item_id>/', onedrive_views.onedrive_favorites_add, name='onedrive_favorites_add'),
    path('onedrive/favorites/<str:item_id>/remove/', onedrive_views.onedrive_favorites_remove, name='onedrive_favorites_remove'),
    # OneDrive Banbury-managed trash
    path('onedrive/trash/', onedrive_views.onedrive_trash_list, name='onedrive_trash_list'),
    path('onedrive/trash/clear/', onedrive_views.onedrive_trash_clear, name='onedrive_trash_clear'),
]
