from django.urls import path
from . import views

urlpatterns = [
    path("add_file/", views.add_file, name="add_file"),
    path("add_files/", views.add_files, name="add_files"),
    path("add_scanned_folder/", views.add_scanned_folder, name="add_scanned_folder"),
    path("delete_files/", views.handle_delete_files, name="add_files"),
    path("update_files/", views.handle_update_files, name="add_files"),
    path("getfileinfo/", views.getfileinfo, name="getfileinfo"),
    path("get_files_from_filepath/", views.get_files_from_filepath, name="get_file_info_from_filepath"),
    path("paginated_get_files_info/", views.paginated_get_files_info, name="paginated_get_files_info"),
    path("getpartialfileinfo/",views.get_partial_file_info,name="getpartialfileinfo",),
    path("search_file/", views.search_file, name="search_file"),
    path("get_scanned_folders/", views.get_scanned_folders, name="get_scanned_folders"),
    path("remove_scanned_folder/", views.remove_scanned_folder, name="remove_scanned_folder"),
    path("share_file/", views.share_file, name="share_file"),
    path("make_file_public/", views.make_file_public, name="make_file_public"),
    path("make_file_private/", views.make_file_private, name="make_file_private"),
    path("get_shared_files/", views.get_shared_files, name="get_shared_files"),
    path("get_shared_files_from_filepath/", views.get_shared_files_from_filepath, name="get_shared_files_from_filepath"),
    path("upload_to_s3/", views.upload_to_s3, name="upload_to_s3"),
    path("get_s3_files/", views.get_s3_files, name="get_s3_files"),
    path("search_s3_files/", views.search_s3_files_view, name="search_s3_files"),
    path("download_s3_file/<str:file_id>/", views.download_s3_file_view, name="download_s3_file"),
    path("delete_s3_file/<str:file_id>/", views.delete_s3_file_view, name="delete_s3_file"),
    path("delete_multiple_s3_files/", views.delete_multiple_s3_files_view, name="delete_multiple_s3_files"),
    # Google Drive endpoints
    path("google_drive/list_files/", views.google_drive_list_files, name="google_drive_list_files"),
    path("google_drive/check_credentials/", views.google_drive_check_credentials, name="google_drive_check_credentials"),
    path("google_drive/oauth_callback/", views.google_drive_oauth_callback, name="google_drive_oauth_callback"),
    path("google_drive/remove_credentials/", views.google_drive_remove_credentials, name="google_drive_remove_credentials"),
    path("google_drive/download_file/<str:file_id>/", views.google_drive_download_file, name="google_drive_download_file"),
    path("google_drive/upload_file/", views.google_drive_upload_file, name="google_drive_upload_file"),
    path("google_drive/create_file/", views.google_drive_create_file, name="google_drive_create_file"),
    path("google_drive/update_file/<str:file_id>/", views.google_drive_update_file, name="google_drive_update_file"),
    path("google_drive/delete_file/<str:file_id>/", views.google_drive_delete_file, name="google_drive_delete_file"),
    # Gmail endpoints
    path("gmail/search", views.gmail_search, name="gmail_search"),
    path("gmail/message/<str:message_id>", views.gmail_get_message, name="gmail_get_message"),
    path("gmail/thread/<str:thread_id>", views.gmail_get_thread, name="gmail_get_thread"),
    path("gmail/threads", views.gmail_list_threads, name="gmail_list_threads"),
    path("gmail/draft", views.gmail_create_draft, name="gmail_create_draft"),
    path("gmail/send", views.gmail_send_message, name="gmail_send_message"),
    path("gmail/reply", views.gmail_send_reply, name="gmail_send_reply"),
    path("gmail/check_access", views.gmail_check_access, name="gmail_check_access"),
    path("gmail/signature", views.gmail_get_signature, name="gmail_get_signature"),
    path("gmail/send_with_signature", views.gmail_send_message_with_signature, name="gmail_send_message_with_signature"),
    # Google Calendar endpoints
    path("google_calendar/check_access", views.google_calendar_check_access, name="google_calendar_check_access"),
    path("google_calendar/events", views.google_calendar_list_events, name="google_calendar_list_events"),
    path("google_calendar/event/<str:calendar_id>/<str:event_id>", views.google_calendar_get_event, name="google_calendar_get_event"),
    path("google_calendar/event", views.google_calendar_create_event, name="google_calendar_create_event"),
    path("google_calendar/event", views.google_calendar_update_event, name="google_calendar_update_event"),
    path("google_calendar/event/<str:calendar_id>/<str:event_id>", views.google_calendar_delete_event, name="google_calendar_delete_event"),
]
